// <auto-generated />
namespace BancoDeQuestoes.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _020520172 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_020520172));
        
        string IMigrationMetadata.Id
        {
            get { return "201705021914168_02052017-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
