// <auto-generated />
namespace BancoDeQuestoes.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _220520171 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_220520171));
        
        string IMigrationMetadata.Id
        {
            get { return "201705231942447_22052017-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
