// <auto-generated />
namespace BancoDeQuestoes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inscr_bq_mestre_formacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inscr_bq_mestre_formacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201704062050227_inscr_bq_mestre_formacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
