// <auto-generated />
namespace BancoDeQuestoes.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Projeto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Projeto));
        
        string IMigrationMetadata.Id
        {
            get { return "201704100238270_projeto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
